name: FQA Automated Tests for Online Food Store

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'The test suite to run (test_alcoholic.py, test_login_page.py, test_cost_calculation.py, test_rate_product_new.py, test_registration.py)'
        default: 'test_login_page.py'
        required: true
        type: string
      browser:
        description: 'Specify which browser to use (chrome, firefox, etc.)'
        default: 'chrome'
        required: true
        type: string

jobs:
  run-tests:
    runs-on: macos-latest 

    steps:
    - name: Check out the code
      uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2  
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Pytest Tests
      run: |
        pytest tests/${{ github.event.inputs.test_suite }}

    - name: Report test results
      if: success() || failure()
      run: |
        echo "Test run completed. Check results above."
